apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mtcnnfd.fullname" . }}
  labels:
    app: "{{ template "mtcnnfd.fullname" . }}"
    chart: "{{ template "mtcnnfd.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "mtcnnfd.fullname" . }}"
      release: {{ .Release.Name | quote }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "mtcnnfd.fullname" . }}"
        chart: "{{ template "mtcnnfd.chart" . }}"
        release: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.metrics.podAnnotations }}
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
{{- include "mtcnnfd.imagePullSecrets" . | indent 6 }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "status.localhost"
      containers:
      - name: mtcnnfd
        image: {{ template "mtcnnfd.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        # env:
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /run
            port: {{ ternary "https" "http" .Values.healthcheckHttps }}
            {{- if .Values.healthcheckHttps }}
            scheme: HTTPS
            {{- end }}
          {{- if .Values.livenessProbeHeaders }}
            httpHeaders:
{{ toYaml .Values.livenessProbeHeaders | indent 14 }}
          {{- end }}
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
          httpGet:
            path: /run
            port: {{ ternary "https" "http" .Values.healthcheckHttps }}
            {{- if .Values.healthcheckHttps }}
            scheme: HTTPS
            {{- end }}
          {{- if .Values.readinessProbeHeaders }}
            httpHeaders:
{{ toYaml .Values.readinessProbeHeaders | indent 14 }}
          {{- end }}
{{ toYaml .Values.readinessProbe | indent 10 }}
        # volumeMounts:
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: {{ template "mtcnnfd.metrics.image" . }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        command: [ '/bin/apache_exporter', '-scrape_uri', 'http://status.localhost:80/server-status/?auto']
        ports:
        - name: metrics
          containerPort: 9117
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
{{- if .Values.sidecars }}
{{ toYaml .Values.sidecars | indent 6 }}
{{- end }}
      volumes:
      {{- if and .Values.allowOverrideNone .Values.customHTAccessCM}}
      - name: custom-htaccess
        configMap:
          name: {{ template "mtcnnfd.customHTAccessCM" . }}
      {{- end }}
      - name: mtcnnfd-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "mtcnnfd.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{ end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
